### ISSUE TITLE
Could we use histogram matching and threshold cutting to normalize all the data before segmentation?

### ISSUE THREAD

**Issue by Barnonewdm** [xamyzhao/brainstorm#1]
Just question about the appearance transformer.

As shown in the paper, the intensity variance of brain T1 MR images seems to be caused by no histogram matching. Could traditional pre-processing overcomes the mentioned appearance variance, especially of brain MR image? What kind of specific appearance variance could the appearance transformer solve?

Best,
Dongming

**Comment by adalca** [comment]
@Barnonewdm,

Yes, you could try to do some intensity normalization preprocessing, and depending on the data, this may indeed work. In this case, (if it works on *all* data, including test data), the appearance transform might not be necessary. However, in several problems we've tackled in the past, especially on noisier, highly variable clinical data acquisitions, appearance normalization via methods like histogram matching tended to fail, so we wanted a method that does not require this normalization done a priori.

In brainstorm, note that the appearance transformer does not need to be perfectly accurate -- instead, because of the way we regularize it smoothly, the transformer simply needs to approximate an appearance transform that characterizes the type of appearance present in this image, so that our method can synthesize a similar image with accurate label.

Hope this helps!

**Comment by Barnonewdm** [comment]
@adalca
Could it be interpreted as the appearance transformer actually copes with style transfer instead of the noise removment？This style variance exits even on the same midality (T1, brain) due to the highly variant data acquisitions. The exact style transfer is unable to be easily normalized by histogram matching?

**Comment by adalca** [comment]
@Barnonewdm yes, exactly!
