### ISSUE TITLE
Training a segmentation network

### ISSUE THREAD

**Issue by lfxuan** [xamyzhao/brainstorm#17]
Thank you very much for your excellent work. Now I am running your code. The sample data provided by you are used in the dataset. The trained models are all in the experience / folder. There are the following confusion points. Please help me to answer them:            1. Python main.py fss -- gpu 0 -- data mri-100unlabeled (’ fss’ should be changed to’ seg’). If the execution does not specify flags, but I specify space and appearance models in seg_model_arch_params, does the resulting segmentation network model use the 
aug_tm method by default?            
2. After completing the training of network segmentation, I tried to evaluate. I readed the code of evaluate_segmenters.py and found that there was no voxelmorph file. The loss.py file only had the project https://github.com/voxelmorph/voxelmorph. How can I solve this problem.

**Comment by xamyzhao** [comment]
Thanks for the suggestion!

1. The segmentation model should perform no augmentation by default if no "aug_..." flags are set.
2. Voxelmorph is implemented in the project https://github.com/voxelmorph/voxelmorph. You can use the code there to train a voxelmorph model. Alternatively, you can use your trained spatial transformation ("flow_fwd") model to perform single atlas segmentation, since it uses the same architecture.

**Comment by lfxuan** [comment]
Amy,Thank you very much for your reply! If I didn't use the enhanced training segmentation network before, can I do the last step to evaluate the segmentation network? If so, do I need to prepare the data set for the mri-csts2-test in ds_key ='mri-csts2-test '？

**Comment by xamyzhao** [comment]
Sorry, I missed this message! You'll need to prepare the test data in a separate folder.
