### ISSUE TITLE
Is this applicable to images taken by endoscope

### ISSUE THREAD

**Issue by wanglamao** [xamyzhao/brainstorm#20]
Hi,

Thank you for the great work. I have a question about whether this data augmentation method could be applied to natural medical images such as images that are taken by a endoscope? Thank you!

**Comment by xamyzhao** [comment]
Thanks for your interest! This data augmentation method works best when you have input images with exact correspondences (i.e. you can match all of the anatomy in one image to the anatomy in another). It also works best on images without occlusion (such as 3D MRIs), since it is not explicitly designed to handle occlusions. My guess is that endoscope images contain significant occlusions, so this might not work well.

**Comment by wanglamao** [comment]
Thank you very much for your answer! 谢谢姐姐了
