### ISSUE TITLE
Train the transform model on my own dataset.

### ISSUE THREAD

**Issue by JessicaChanzc** [xamyzhao/brainstorm#21]
Thank you for your excellent work!
Now I want to have a try on my own dataset (2D gray CT image of lung). Can this transform model work on this type data? 
If you can give me some advice, I'll be very appreciate:)

**Comment by xamyzhao** [comment]
Thank you for your interest! The spatial transformation will work best with 3D data, since it is not explicitly designed to handle occlusions. If your 2D images do not contain a lot of occlusions, and each image contains the same anatomical regions such that they can be registered to each other, then this model might work.
