### ISSUE TITLE
'OASIS_OAS1_0327_MR1_mri_talairach_orig'

### ISSUE THREAD

**Issue by Qingyuncookie** [xamyzhao/brainstorm#3]
In the 35nd line of the main.py, there is a key "use_subjects_as_source" whose content is ['OASIS_OAS1_0327_MR1_mri_talairach_orig'], I have searched all the files and can't find this file. I'm not sure if this is a MRI data or not, and I don't understand what it is used for, please help me, thank you very much !

**Comment by xamyzhao** [comment]
'OASIS_OAS1_0327_MR1_mri_talairach_orig' is the name of the subject that we selected to be our atlas in our experiments, and we use the name to load the corresponding MRI volume and segmentations. Since we do not include the MRI data in this repo, you would need to download the scans from the OASIS dataset on your own, or select your own atlas. Sorry about the confusion!
